import { describe, expect, test } from "vitest";

import {
  END_MARKER,
  GENERATED_NOTICE,
  START_MARKER,
} from "../src/sync/markers.js";

describe("TreeMark synchronization markers", () => {
  test("exports the canonical start marker", () => {
    expect(START_MARKER).toBe(
      "<!-- treemark:start -->",
    );
  });

  test("exports the canonical end marker", () => {
    expect(END_MARKER).toBe(
      "<!-- treemark:end -->",
    );
  });

  test("exports the canonical generated notice", () => {
    expect(GENERATED_NOTICE).toBe(
      "<!-- Generated by TreeMark. Do not edit manually. -->",
    );
  });
});