export const START_MARKER =
  "<!-- treemark:start -->";

export const END_MARKER =
  "<!-- treemark:end -->";

export const GENERATED_NOTICE =
  "<!-- Generated by TreeMark. Do not edit manually. -->";